fixed old bug with package_installer, when a package in a set of packages is missing, the installer fails, now it checks for installation candidates like the other package installer stuff does in sm-lib-package-install

diff --git a/sm-lib-apt-tools b/sm-lib-apt-tools
--- a/sm-lib-apt-tools
+++ b/sm-lib-apt-tools
@@ -1,8 +1,8 @@
 #!/bin/bash
 ########################################################################
 ####  Script Name: sm-lib-apt-tools
-####  version: 1.23.38
-####  Date: 2014-10-09
+####  version: 1.23.39
+####  Date: 2015-05-19
 
 ####  Copyright (C) Harald Hope 2005-2014
 ####  This program is free software; you can redistribute it and/or modify it under
@@ -192,15 +192,16 @@ package_installer()
 	#local smPref=$( sm_pref_tester $prefId )
 	local packageExists='' package='' packageTemp='' dumpSpace=''
 	local installType=$2 doYes=' -y' forceIt='' extraInstallArgs=$3
-	local installAlways='' installAbsent='' installPresent=''
+	local installAlways='' installAbsent='' installPresent='' packages=''
 	local installError=0 forceError=0 installIt='' install='install'
 	local altText1='Installing' altText2=' to update your system'
-	local testOption='ii' packagePlural1='' packagePlural2='is'
+	local testOption='ii' packagePlural1='' packagePlural2='is' bMultiPackage='false'
 
 	# set the plural text
 	if [ "$( wc -w <<< $1 )" -gt 1 ];then
 		packagePlural1='s'
 		packagePlural2='are'
+		bMultiPackage='true'
 	fi
 
 	case $installType in
@@ -257,14 +258,24 @@ package_installer()
 		do
 			packageTemp=$( package_tester $package $testOption )
 			# here we handle cases where one of several is null, so we want to install all
-			if [ -z "$packageTemp" ];then
+			# however, for multi sets of packages, we don't want to not install it if one is missing
+			if [ -z "$packageTemp" -a "$bMultiPackage" == 'false' ];then
 				installIt='true'
 			fi
 			# don't add a space or the -n test will be true
 			packageExists="$packageExists$packageTemp"
+			
+			if [ -n "$( check_package_status $package 'c' )" ];then
+				echo "${S}Adding ${C}$package${S} to install group.${N}"
+				packages="$packages$package "
+			else
+				echo "${M}Sorry, ${C}$package${M} is not available in ${C}Debian $SYSTEM_BASE${M}!${N}"
+			fi
 		done
 		# just want to make sure here that's it's going to be truly null
 		packageExists=$( echo $packageExists | sed 's/\s//g' )
+		log_function_data "packages install list: $packages"
+		log_function_data "packageExists install list: $packageExists"
 	fi
 	# nullify the entire set if one member is null
 	if [ "$installIt" == 'true' ];then
@@ -278,31 +289,33 @@ package_installer()
 	#  -o -n "$packageExists"
 	# cases: 1-always do it; 2-do if absent and to install misssing;
 	# 3-do if present required update
-	if [ "$installAlways" == 'true' ] || [ "$installAbsent" == 'true' -a -z "$packageExists" ] || [ "$installPresent" == 'true' -a -n "$packageExists" ];then
-		echo # just for cosmetics here, for multiple packages separates
-		echo "${SPACER}${S}$altText1 ${C}$1${S}$altText2...${N}"
+	if [ -n "$packages" ];then
+		if [ "$installAlways" == 'true' ] || [ "$installAbsent" == 'true' -a -z "$packageExists" ] || [ "$installPresent" == 'true' ];then
+			echo # just for cosmetics here, for multiple packages separates
+			echo "${SPACER}${S}$altText1 ${C}$packages${S}$altText2...${N}"
 
-		if [ "$forceIt" == 'true' ];then
-			log_function_data "install -f pre: $APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes"
-			$APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes 2>>$LOG_FILE 2>&1
+			if [ "$forceIt" == 'true' ];then
+				log_function_data "install -f pre: $APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes"
+				$APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes 2>>$LOG_FILE 2>&1
+			fi
+			log_function_data "install main: $APT_TYPE $install $WITHOUT_RECOMMENDS $doYes $extraInstallArgs $1"
+			$APT_TYPE $install $WITHOUT_RECOMMENDS $doYes $extraInstallArgs $packages 2>>$LOG_FILE 2>&1 || installError=$?
+			if [ "$forceIt" == 'true' ];then
+				log_function_data "install -f post: $APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes"
+				$APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes 2>>$LOG_FILE 2>&1 || forceError=$?
+			fi
+		# if user install and already installed...
+		elif [ "$installAbsent" == 'true' -a -n "$packageExists"  ];then
+			echo "${SPACER}${M}The package$packagePlural1: ${C}$packages"
+			echo "${SPACER}${M}$packagePlural2 already installed on your system. Continuing...${N}"
+			echo
 		fi
-		log_function_data "install main: $APT_TYPE $install $WITHOUT_RECOMMENDS $doYes $extraInstallArgs $1"
-		$APT_TYPE $install $WITHOUT_RECOMMENDS $doYes $extraInstallArgs $1 2>>$LOG_FILE 2>&1 || installError=$?
-		if [ "$forceIt" == 'true' ];then
-			log_function_data "install -f post: $APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes"
-			$APT_TYPE install $WITHOUT_RECOMMENDS -f $doYes 2>>$LOG_FILE 2>&1 || forceError=$?
-		fi
-	# if user install and already installed...
-	elif [ "$installAbsent" == 'true' -a -n "$packageExists"  ];then
-		echo "${SPACER}${M}The package$packagePlural1: ${C}$1"
-		echo "${SPACER}${M}$packagePlural2 already installed on your system. Continuing...${N}"
-		echo
 	fi
 	# only do error handling if either install only, or force/install cases went bad
 	if [ "$forceError" -gt 0 ] || [ "$forceIt" != 'true' -a "$installError" -gt 1 ];then
-		echo "${SPACER}${E}There was a problem with install of: ${C}$1${N}"
+		echo "${SPACER}${E}There was a problem with install of: ${C}$packages${N}"
 		echo
-		log_function_data "Error: $installError with install of $1"
+		log_function_data "Error: $installError with install of $packages"
 		eval $LOGUE
 		return 1
 	else
