package install, more fixes to google earth, now grabs deb directly from google, that deb will create a google-earth.list file so the package will be properly installed and updated after that.
Added in apt-get install -f as well which pulls in any missing packages from dpkg -i <package>

and that's that.

diff --git a/sm-lib-package-install b/sm-lib-package-install
--- a/sm-lib-package-install
+++ b/sm-lib-package-install
@@ -1,12 +1,12 @@
 #!/bin/bash
 ########################################################################
 ####  Script Name: sm-lib-package-install
-####  version: 3.4.28
+####  version: 3.4.29
 ####  Date: 2014-08-08
 
 ####  Copyright (C) Harald Hope 2005-2014
 ####  This program is free software; you can redistribute it and/or modify it under
-####  the terms of the GNU General Public License as published by the Free Software
+####  the terms of the GNU General Public License as published by the Free Software 
 ####  Foundation; either version 2 of the License, or (at your option) any later version.
 
 ####  This program is distributed in the hope that it will be useful, but WITHOUT
@@ -56,7 +56,7 @@ package_group_installer()
 	local qt4Config=''
 	local lxdeLMC='libmenu-cache0' lxdeMD='lxmenu-data' lxdeSE='lxsession-edit'
 	local lxdeIP='lxinput' lxdeM='lxmusic'
-
+	
 	# note: these packages are not in every Debian level
 	if [ -z "$( check_package_status 'epdfview' )" ];then
 		pdfLight='xpdf'
@@ -1502,39 +1502,60 @@ reinstall_skype()
 install_google_earth()
 {
 	eval $LOGPS
-	local goog='Google Earth' uninstallPackage=''
+	local goog='Google Earth' uninstallPackage='' install_deb='google-earth-stable_current_i386.deb'
+	local download_error=0 google_earth_package='googleearth-package'
+	
+	if [ "$BITS" == '64' ];then
+		install_deb='google-earth-stable_current_amd64.deb'
+	fi
+	download_path=" http://dl.google.com/dl/earth/client/current/$install_deb"
 	echo $LINE
 	echo "${S}Starting ${C}$goog${S} installer."
 	echo
-	echo "Adding ${C}$goog${S} installer file and creating ${C}$goog${S} deb...${N}"
-	package_group_installer plain google-earth 'update_to_nonfree_sources'
+	echo "Getting ${C}$goog${S} installer file and installing ${C}$goog${S} deb...${N}"
+	# package_group_installer plain google-earth 'update_to_nonfree_sources'
 	cd /var/cache/apt/archives
+	wget -Nc $download_path || download_error=$?
 	# force required to build as root
-	make-googleearth-package --force 2>>$LOG_FILE 2>&1
-	
-	if [ -n "$( ls googleearth*.deb 2>/dev/null )" ];then
-		uninstallPackage="$( package_tester '(googleearth)' )"
-		if [ -n "$uninstallPackage" ];then
-			package_remover "$uninstallPackage" 'purge' 'group'
-		fi
-		echo "${S}Installing ${C}$goog${S} deb...${N}"
-		dpkg -i googleearth*.deb 2>>$LOG_FILE 2>&1
-		# this will pull in any needed packages the deb required
-		apt-get install -f -y
-		if [ "$APT_TYPE" == 'aptitude' ];then
-			$APT_TYPE install googleearth 2>>$LOG_FILE 2>&1
-		fi
-		cd $SCRIPT_HOME
-		#echo "${S}Cleaning up ${C}$goog${S} installer stuff...${N}"
-		# package_remover 'googleearth-package' 'purge -y'
-		echo "${S}Completed install of ${C}$goog${S}.${N}"
-		echo $LINE
-		echo "${S}To start ${C}$goog${S}, simply run the command from your desktop: ${C}googleearth${N}"
-	else
+	# make-googleearth-package --force 2>>$LOG_FILE 2>&1
+	# http://dl.google.com/dl/earth/client/current/google-earth-stable_current_i386.deb
+	# http://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb
+	if [ "$download_error" -gt 0 ];then
 		echo $ELINE
-		echo "${E}Oh, too bad, the ${C}googleearth deb${E} package failed to build, sorry about that."
-		echo "${S}Check forums and other information to see if the Debian package builder is broken."
-		echo "Unable to install googleearth using this method, sorry.${N}"
+		echo "${E}Oh, too bad, the ${C}googleearth deb${E} package failed to download."
+		echo "Please let the maintainer know, or try again in a few minutes in case it's your"
+		echo "network connection that failed.${N}"
+	else
+		if [ -f "$install_deb" ];then
+			uninstallPackage="$( package_tester '(googleearth)' )"
+			echo "${S}Cleaning up previous ${C}$goog${S} materials/packages...${N}"
+			if [ -n "$uninstallPackage" ];then
+				package_remover "$uninstallPackage" 'purge -y' 'group'
+			fi
+			if [ -n "$google_earth_package" ];then
+				package_remover "$google_earth_package" 'purge -y' 'group'
+			fi
+			echo "${S}Installing ${C}$goog${S} deb...${N}"
+			dpkg -i $install_deb 2>>$LOG_FILE 2>&1
+			# this will pull in any needed packages the deb required
+			echo "${S}Installing any missing packages for ${C}$install_deb${S}...${N}"
+			apt-get install -f -y
+# 			if [ "$APT_TYPE" == 'aptitude' ];then
+# 				$APT_TYPE install googleearth 2>>$LOG_FILE 2>&1
+# 			fi
+			rm -f $install_deb
+			cd $SCRIPT_HOME
+			#echo "${S}Cleaning up ${C}$goog${S} installer stuff...${N}"
+			# package_remover 'googleearth-package' 'purge -y'
+			echo "${S}Completed install of ${C}$goog${S}.${N}"
+			echo $LINE
+			echo "${S}To start ${C}$goog${S}, simply run the command from your desktop: ${C}google-earth${N}"
+		else
+			echo $ELINE
+			echo "${E}Oh, too bad, the ${C}google earth deb${E} package failed to download, sorry about that."
+			echo "${S}Check forums and other information to see if the Debian package builder is broken."
+			echo "Unable to install googleearth using this method, sorry.${N}"
+		fi
 	fi
 
 	print_hec
