Added in protections against corrupted or incomplete kernel zip downloads

diff --git a/sm-lib-kernel-install b/sm-lib-kernel-install
--- a/sm-lib-kernel-install
+++ b/sm-lib-kernel-install
@@ -1,10 +1,10 @@
 #!/bin/bash
 ########################################################################
 ####  Script Name: sm-lib-kernel-install
-####  version: 2.12.15
-####  Date: 2021-01-03
+####  version: 2.12.16
+####  Date: 2022-07-26
 
-####  Copyright (C) Harald Hope 2005-2021
+####  Copyright (C) Harald Hope 2005-2022
 ####  The following functions use core logic by Kel Modderman (kelmo)
 ####  extra_module_installer update_kernel_links install_the_apt_kernel_module
 ####  install_apt_kernel_modules
@@ -742,15 +742,34 @@ download_kernel()
 {
 	eval $LOGUS
 	local FullFileName=$1 kernelDownloadPath=''
-	local downloadFailed=''
+	local downloadFailed='' message='' error=0 local test=0
 	local ua="-U s-tools/kernels.$FullFileName"
+	local fullPath="$SCRIPT_DOWNLOAD_KERNELS$BITS'/'$FullFileName"
 
 	# now we'll grab the kernel zip file from home base
-	wget $ua -T$TIME_OUT -t2 -Nc $SCRIPT_DOWNLOAD_KERNELS$BITS'/'$FullFileName || downloadFailed='true'
+	wget $ua -T$TIME_OUT -t2 -Nc $fullPath || error=$?
+	if [ "$error" -gt 0 ];then
+		message="Download of kernel failed with error: $error"
+		downloadFailed='true'
+	# verify download
+	elif [ ! -s "$fullPath" ];then
+		downloadFailed='true'
+		message="Download of kernel worked but file is empty. Removing file."
+		rm -f $fullPath
+	else
+		unzip -t $fullPath || test="$?"
+		if [ "$test" -gt 0 ];then
+			downloadFailed='true'
+			message="Kernel zip file downloaded and is not empty but is corrupted. Removing file."
+			rm -f $fullPath
+		fi
+	fi
 
 	if [ "$downloadFailed" == 'true' ];then
 		echo "${E}The default kernel download location: ${C}$SCRIPT_DOWNLOAD_KERNELS"
-		echo "${E}could not be accessed, or it doesn't have the kernel you requested."
+		echo "${E}could not be accessed, or the kernle file did not download correctly."
+		echo "";
+		echo $message
 		echo
 		echo "${S}If kernel has not been previously downloaded here, the script will exit.${N}"
 		eval $LOGUE
