more module cleanup and tweaks

diff --git a/sm-lib-kernel-install b/sm-lib-kernel-install
--- a/sm-lib-kernel-install
+++ b/sm-lib-kernel-install
@@ -1,7 +1,7 @@
 #!/bin/bash
 ########################################################################
 ####  Script Name: sm-lib-kernel-install
-####  version: 2.10.14
+####  version: 2.10.15
 ####  Date: April 1 2009
 
 ####  Copyright (C) Harald Hope 2005-2009
@@ -1278,7 +1278,7 @@ extra_module_installer()
 	eval $LOGUS
 	local kernelVersion=$1 moduleName=$2 argMissing='' driverTest=''
 	local filename='' tarball='' module='' message='' extra='' buildFailed=0
-	local moduleSourcePresent=''
+	local moduleSourcePresent='' modulePackage=''
 
 	case $moduleName in
 		madwifi)
@@ -1304,44 +1304,48 @@ extra_module_installer()
 	echo "${S}Checking ${C}$module${S} status now...${N}"
 	# note: etch doesn't support -k option but that's ok, it will soon be lenny
 	driverTest=$( /sbin/modinfo -k $CURRENT_KERNEL -F filename $filename 2>/dev/null )
-	modulePackage="$( dpkg -S $driverTest 2>/dev/null )"
+	
 	# hints for module to be built
 	if [ -n "$1" -a -n "$2" ];then
 		#/sbin/modinfo -k $CURRENT_KERNEL -F filename $filename 2>/dev/null 2>&1
-		if [ -n "$driverTest" -a -z "$( grep 'linux-image-' <<< $modulePackage )" ];then
-			if [ -n "$moduleSourcePresent" ];then
-	# 			echo "${S}Checking to see if ${C}$extra$module${S} can be built for your wifi card...${N}"
-	# 			if [ -f /usr/src/${tarball} ] && which m-a >/dev/null
-	# 			then
-				echo "${S}Starting build of your ${C}$module${S} module now...${N}"
-				# user setup madwifi with module-assistant already
-				# we may as well do that for him again now
-				if [ -d /usr/src/modules/${module}/ ];then
-					rm -rf /usr/src/modules/${module}/
-				fi
-				# this will pull in the source if required etc...
-				m-a --text-mode --non-inter -l $kernelVersion a-i $module || buildFailed=$?
-	# 			else
-				if  [ "$buildFailed" -eq 249 ];then # this is pre-exisisting module error
-					echo $MLINE
-					echo "${C}error 249${M} just means ${C}$module${M} was already installed on your new kernel. "
-					echo "Sometimes ${C}$SCRIPT_NAME${M} and the current sidux apt kernel installers"
-					echo "might be slightly out of sync, that's ok though.${N}"
-				elif [ "$buildFailed" -gt 0 ];then
-					echo $WLINE
-					echo "${E}The ${C}m-a${E} build of your module exited with error code ${C}$buildFailed${S}"
-					echo -e "$message"
-					echo
-					echo "Please report any critical errors you might get on sidux.com forums,"
-					echo "especially the exit error number.${S}"
-					echo $WLINE
+		if [ -n "$driverTest" ];then
+			# this is a slow test so only run if needed
+			modulePackage="$( dpkg -S $driverTest 2>/dev/null )"
+			if [ -n "$modulePackage" -a -z "$( grep 'linux-image-' <<< $modulePackage )" ];then
+				if [ -n "$moduleSourcePresent" ];then
+		# 			echo "${S}Checking to see if ${C}$extra$module${S} can be built for your wifi card...${N}"
+		# 			if [ -f /usr/src/${tarball} ] && which m-a >/dev/null
+		# 			then
+					echo "${S}Starting build of your ${C}$module${S} module now...${N}"
+					# user setup madwifi with module-assistant already
+					# we may as well do that for him again now
+					if [ -d /usr/src/modules/${module}/ ];then
+						rm -rf /usr/src/modules/${module}/
+					fi
+					# this will pull in the source if required etc...
+					m-a --text-mode --non-inter -l $kernelVersion a-i $module || buildFailed=$?
+		# 			else
+					if  [ "$buildFailed" -eq 249 ];then # this is pre-exisisting module error
+						echo $MLINE
+						echo "${C}error 249${M} just means ${C}$module${M} was already installed on your new kernel. "
+						echo "Sometimes ${C}$SCRIPT_NAME${M} and the current sidux apt kernel installers"
+						echo "might be slightly out of sync, that's ok though.${N}"
+					elif [ "$buildFailed" -gt 0 ];then
+						echo $WLINE
+						echo "${E}The ${C}m-a${E} build of your module exited with error code ${C}$buildFailed${S}"
+						echo -e "$message"
+						echo
+						echo "Please report any critical errors you might get on sidux.com forums,"
+						echo "especially the exit error number.${S}"
+						echo $WLINE
+						print_hec
+					fi
+				else
+					echo $ELINE
+					echo "${E}There is no ${C}$module-source${E} package for ${C}$module${E} available in apt."
+					echo "${S}Cannot build your module using ${C}m-a${S}, sorry.${N}"
 					print_hec
 				fi
-			else
-				echo $ELINE
-				echo "${E}There is no ${C}$module-source${E} package for ${C}$module${E} available in apt."
-				echo "${S}Cannot build your module using ${C}m-a${S}, sorry.${N}"
-				print_hec
 			fi
 		fi
 	else
