added more grub gfx installer options

diff --git a/sm-lib-misc-tweaks b/sm-lib-misc-tweaks
--- a/sm-lib-misc-tweaks
+++ b/sm-lib-misc-tweaks
@@ -1,7 +1,7 @@
 #!/bin/bash
 ########################################################################
 ####  Script Name: sm-lib-misc-tweaks
-####  version: 1.20.0
+####  version: 1.21.0
 ####  Date: August 16 2008
 
 ####  Copyright (C) Harald Hope 2005-2008
@@ -713,70 +713,79 @@ install_kmenu_icon()
 grub_gfx_selector()
 {
 	eval $LOGPS
-	echo $LINE
-	echo "${S}Please select one of the following grub options."
-	echo
-	echo "Each updates ${C}$GRUB_PATH${S} to use the new grub image as well."
-	echo 
-	echo "Items 3-5 are by me, h2, and are very simple, just colored fonts on black background."
-	echo $LINE
-	echo "${C}1${S} - ${C}grub-gfx-cathbard-1${S} A cathbard black/red design, with debian swirls."
-	echo "    down the left side. Updates ${C}$GRUB_PATH${S} as well."
-	echo
-	echo "${C}2${S} - ${C}grub-gfx-sidux-1${S} Original sidux grub graphics design,"
-	echo "    Simple black/red motiff."
-	echo
-	echo "${C}3${S} - ${C}grub-gfx-debian-1${S} Simple black, with large blue Debian text."
-	echo "${C}4${S} - ${C}grub-gfx-debian-sidux${S} Simple black, with blue Debian, small red sidux."
-	echo "${C}5${S} - ${C}grub-gfx-debian-smxi${S} Simple black, with blue Debian, small smxi (in smxi colors)."
-	echo
-	echo "${C}6${S} - ${C}grub-gfx-restore${S} Returns to standard sidux grub default gfx."
-	echo
-	echo "${C}7${S} - Returns to main menu."
-	echo $LINE
-	echo $SLE
-	echo $LINE
-	options="grub-gfx-cathbard-1 grub-gfx-sidux-1 grub-gfx-debian-1 grub-gfx-debian-sidux grub-gfx-debian-smxi grub-gfx-restore continue"
-	select opt in $options
-	do
-		case $opt in
-			grub-gfx-cathbard-1)	
-				grub_gfx_message_installer 'cath.brd'
-				repeat='true'
-				;;
-			grub-gfx-sidux-1)	
-				grub_gfx_message_installer 'sidux.original'
-				repeat='true'
-				;;
-			grub-gfx-debian-1)	
-				grub_gfx_message_installer 'debian'
-				repeat='true'
-				;;
-			grub-gfx-debian-sidux)	
-				grub_gfx_message_installer 'debian.sidux'
-				repeat='true'
-				;;
-			grub-gfx-debian-smxi)	
-				grub_gfx_message_installer 'debian.smxi'
-				repeat='true'
-				;;
-			grub-gfx-restore)
-				restore_grub_gfx
-				repeat='true'
-				;;
-			continue)
-				echo "${S}Ok, you are ready to go on now.${N}"
-				;;
-			*)
-				print_error opt
-				;;
-		esac
-		break
-	done
-	eval $LOGPE
-	if [ "$repeat" == 'true' ]
+	grub_gfxboot_question
+	
+	if [ "$?" -eq 0 ]
 	then
-		grub_gfx_selector
+		echo $LINE
+		echo "${S}Please select one of the following grub options."
+		echo
+		echo "Each updates ${C}$GRUB_PATH${S} to use the new grub image as well."
+		echo 
+		echo "Items 3-5 are by me, h2, and are very simple, just colored fonts on black background."
+		echo $LINE
+		echo "${C}1${S} - ${C}grub-gfx-cathbard-1${S} A cathbard black/red design, with debian swirls."
+		echo "    down the left side. Updates ${C}$GRUB_PATH${S} as well."
+		echo
+		echo "${C}2${S} - ${C}grub-gfx-sidux-1${S} Original sidux grub graphics design,"
+		echo "    Simple black/red motiff."
+		echo
+		echo "${C}3${S} - ${C}grub-gfx-debian-1${S} Simple black, with large blue Debian text."
+		echo "${C}4${S} - ${C}grub-gfx-debian-sidux${S} Simple black, with blue Debian, small red sidux."
+		echo "${C}5${S} - ${C}grub-gfx-debian-smxi${S} Simple black, with blue Debian, small smxi (in smxi colors)."
+		echo
+		echo "${C}6${S} - ${C}grub-gfx-restore${S} Returns to standard sidux grub default gfx."
+		echo
+		echo "${C}7${S} - Returns to main menu."
+		echo $LINE
+		echo $SLE
+		echo $LINE
+		options="grub-gfx-cathbard-1 grub-gfx-sidux-1 grub-gfx-debian-1 grub-gfx-debian-sidux grub-gfx-debian-smxi grub-gfx-restore continue"
+		select opt in $options
+		do
+			case $opt in
+				grub-gfx-cathbard-1)	
+					grub_gfx_message_installer 'cath.brd'
+					repeat='true'
+					;;
+				grub-gfx-sidux-1)	
+					grub_gfx_message_installer 'sidux.original'
+					repeat='true'
+					;;
+				grub-gfx-debian-1)	
+					grub_gfx_message_installer 'debian'
+					repeat='true'
+					;;
+				grub-gfx-debian-sidux)	
+					grub_gfx_message_installer 'debian.sidux'
+					repeat='true'
+					;;
+				grub-gfx-debian-smxi)	
+					grub_gfx_message_installer 'debian.smxi'
+					repeat='true'
+					;;
+				grub-gfx-restore)
+					restore_grub_gfx
+					repeat='true'
+					;;
+				continue)
+					echo "${S}Ok, you are ready to go on now.${N}"
+					;;
+				*)
+					print_error opt
+					;;
+			esac
+			break
+		done
+		eval $LOGPE
+		if [ "$repeat" == 'true' ]
+		then
+			grub_gfx_selector
+		fi
+	else
+		log_function_data "User opted not to install grub-gfxboot, skipping feature. "
+		echo "${M}Skipping this feature since you didn't chose to install grub-gfxboot.${N}"
+		eval $LOGPE
 	fi
 }
 
@@ -830,12 +839,114 @@ restore_grub_gfx()
 		else
 			echo "${E}No default grub graphic file ${C}/boot/message${E} exists. Unable to"
 			echo "update since there is no default present.${N}"
+			log_function_data "No default grub graphic file: /boot/message"
 		fi
 	else
 		echo "${E}Your ${C}$GRUB_PATH${E} does not appear to have a ${C}gfxmenu${E} item configured yet."
 		echo "Please update it to use this feature.${N}"
 	fi
 	print_hec
+	eval $LOGUE
+}
+
+grub_gfxboot_question()
+{
+	eval $LOGUS
+	local opt='' option='' repeat='' returnValue=0
+	local hasGrubGfx=$(package_tester 'grub-gfxboot' )
+	
+	if [ -z "$hasGrubGfx" ]
+	then
+		echo $LINE
+		echo $LINE
+		echo "${C}1${S} - ${C}yes-install-grub-gfxboot${S} Install missing grub-gfxboot to replace default grub first."
+		echo
+		echo "${C}2${S} - ${C}no-skip-feature${S} - Skips this feature without installing anything."
+		echo $LINE
+		echo $SLE
+		echo $LINE
+		options="yes-install-grub-gfxboot no-skip-feature"
+		select opt in $options
+		do
+			case $opt in
+				yes-install-grub-gfxboot)	
+					install_grub_gfxboot
+					;;
+				no-skip-feature)	
+					returnValue=1
+					;;
+				*)
+					print_error opt
+					;;
+			esac
+			break
+		done
+		eval $LOGUE
+		if [ "$repeat" == 'true' ]
+		then
+			grub_gfxboot_question
+		fi
+		
+	fi
+	return $returnValue
+}
+install_grub_gfxboot()
+{
+	eval $LOGUS
+		
+	# this adds, updates, then removes temp repo
+	check_add_remove_sources 'sidux'
+	package_installer 'grub-gfxboot' 'install-always'
+	# make sure to not keep temp repo data
+	apt_update_handler 'temp-repo'
+	check_gfxboot_in_menu
+	check_message_debian
+	update_grub_install
+	eval $LOGUE
+}
+
+check_gfxboot_in_menu()
+{
+	eval $LOGUS
+	# make sure not commented out etc
+	local gfxGrubExists=$( egrep '^gfxmenu'  $GRUB_PATH )
+	local colorExists=$( egrep '^color[[:space:]]'  $GRUB_PATH )
+	local colorLineNu=$( egrep -in '^color[[:space:]]' $GRUB_PATH | cut -d ':' -f 1 )
+	local grootGrub=$( awk -F= '/^# groot/{print $2}' $GRUB_PATH  )
+	log_function_data "gfxGrubExists: $gfxGrubExists - colorExists: $colorExists - colorLineNu: $colorLineNu - grootGrub: $grootGrub"
+	if [ -z "$gfxGrubExist	s" ]
+	then
+		if [ -n "$colorExists" ]
+		then
+			sed -i "s|^color[[:space:]].*|&\
+gfxmenu $grootGrub/boot/message.debian|" $GRUB_PATH
+		else
+			error_handler 'bad-file-format' $FUNCNAME "$GRUB_PATH: '^color' not found." 
+		fi
+	fi
+	eval $LOGUE
+}
+check_message_debian()
+{
+	eval $LOGUS
+	if [ ! -f /boot/message.debian ]
+	then
+		grub_gfx_message_installer 'debian'
+	fi
+	eval $LOGUE
+}
+
+update_grub_install()
+{
+	eval $LOGUS
+	local grootGrub=$( awk -F= '/^# groot/{print $2}' $GRUB_PATH | sed -r 's/\((.*)\)/\1/' )
+	
+	log_function_data "grootGrub: $grootGrub"
+	echo "${S}Running  ${C}grub-install${S} first time to update grub....${N}"
+	grub-install --recheck --no-floppy $grootGrub
+	echo "${S}Running  ${C}grub-install${S} again...${N}"
+	grub-install --recheck --no-floppy $grootGrub
+	echo "${S}Finished with ${C}grub-gfxboot${S} update.${N}"
 	eval $LOGUE
 }
 
