New feature, by request, update all smxi script libraries and modules at once. Also new option to install rbxi if you want.
rbxi install will download bzip package, extract it, chmod x, then mv contents of package to /usr/local/bin directly.

diff --git a/smxi b/smxi
--- a/smxi
+++ b/smxi
@@ -1,8 +1,8 @@
 #!/bin/bash
 ########################################################################
 ####  Script Name: smxi
-####  version: 8.8.3
-####  Date: January 17 2009
+####  version: 8.9.0
+####  Date: January 19 2009
 ########################################################################
 ####  Copyright (C) Harald Hope 2005-2009
 ####  This program is free software; you can redistribute it and/or modify it under
@@ -211,6 +211,13 @@ LIB_2008_FIXES=''
 MOD_INXI='inxi'
 MOD_GFX='sgfxi'
 MOD_VM='svmi'
+
+# full updater
+UPDATE_ALL="$SCRIPT_NAME $LIB_APT_TOOLS $LIB_CLEAN_UP $LIB_DISTRO_CONVERSIO
+$LIB_DU_FIXES $LIB_GRAPHICS $LIB_KERNEL $LIB_KERNEL_INSTALL $LIB_MISC_TWEAKS
+$LIB_PACKAGE_INSTALL $LIB_PACKAGE_REMOVAL $LIB_WARNING $LIB_2007_FIXES
+$LIB_2008_FIXES_STATIC ${LIB_2008_FIXES_STATIC}_t $MOD_GFX $MOD_VM $MOD_INXI"
+
 # optional user set scripts/download locations
 USER_SCRIPT=''
 USER_SCRIPT_URL=''
@@ -890,6 +897,104 @@ update_scripts()
 	log_function_data "Return: $success"
 	eval $LOGUE
 	return $success
+}
+
+# args $1 - rbxi ( for rbxi install and setup )
+update_all_scripts()
+{
+	check_root
+	local script='' downloadUrl='' verifyDownload='' errorOccurred=''
+	local fullUrl='' completionMessage='Full script component update'
+	local continue=''
+
+	cd $SCRIPT_HOME
+
+	if [ "$1" == 'rbxi' ];then
+		UPDATE_ALL=''
+	fi
+
+	for script in $UPDATE_ALL $1
+	do
+		case $script in
+			inxi)
+				downloadUrl=$SCRIPT_DOWNLOAD_IN$script
+				;;
+			sgfxi)
+				downloadUrl=$SCRIPT_DOWNLOAD_SG$script
+				;;
+			svmi)
+				downloadUrl=$SCRIPT_DOWNLOAD_SV$script
+				;;
+			rb)
+				downloadUrl='smxi.org/rb'
+				completionMessage='Rbxi install'
+				;;
+			*)
+				downloadUrl=$SCRIPT_DOWNLOAD$script
+				;;
+		esac
+
+		echo -n "Downloading $script... "
+		wget -Nqc $downloadUrl
+
+		if [ "$?" -eq 0 ];then
+			echo "downloaded"
+			continue='true'
+		else
+			echo "${W}download failed${N}"
+			errorOccured='true'
+			continue='false'
+			break
+		fi
+
+		if [ "$continue" == 'true' ];then
+			if [ "$1" == 'rbxi' ];then
+				echo "Extracting rbxi data... "
+				tar xjvf rbxi.tar.bz2
+				echo -n "Setting up rbxi... "
+				mv rbxi rb
+				mv rb/* ./
+				rm -f rbxi.tar.bz2
+				rm -fr rb
+				echo "completed"
+			fi
+		fi
+
+		if [ "$continue" == 'true' ];then
+			echo -n "Verifying $script file integrity... "
+			verifyDownload=$( grep '#**EOF**#' $script )
+			if [ -n "$verifyDownload" ];then
+				echo "verified"
+				continue='true'
+			else
+				echo "${W}file is corrupted: test failed${N}"
+				errorOccurred='true'
+				continue='false'
+				break
+			fi
+		fi
+		if [ "$continue" == 'true' ];then
+			case $script in
+				inxi|sgfxi|smxi|svmi|rbxi)
+					echo -n "Making $script executable... "
+					chmod +x $script
+					if [ "$?" -eq 0 ];then
+						echo "done"
+					else
+						errorOccurred='true'
+						echo "${W}chmod +x failed${N}"
+						break
+					fi
+					;;
+			esac
+		fi
+	done
+	if [ "$errorOccurred" == 'true' ];then
+		echo "${W}Exiting because of unexpected error. Please make sure you have a good connection.${N}"
+	else
+		echo "$completionMessage completed."
+	fi
+	exit 0
 }
 
 # args: $1 - file to download; $2 -chm; $3 - repeat try, auto
@@ -1803,9 +1908,8 @@ start_up_tests()
 	# Make sure script is in path set in $SCRIPT_HOME
 	check_script_path
 	# check for correct user status. This script must run as root
-	if [ "$(whoami)" != "root" ];then
-		error_handler 'not-root' $FUNCNAME
-	fi
+	check_root
+
 	# no ubuntu support
 	if [ "$( cat /etc/issue | grep -i -c 'buntu' )" -gt 0 -a ! -f "$EAX" ];then
 		error_handler 'unsupported-distro' $FUNCNAME 'Ubuntu derived'
@@ -1817,6 +1921,13 @@ start_up_tests()
 		error_handler 'unidentified-distro' $FUNCNAME ''
 	fi
 
+}
+
+check_root()
+{
+	if [ "$(whoami)" != "root" ];then
+		error_handler 'not-root' $FUNCNAME
+	fi
 }
 
 # this script must run out of x, and gives option to go into default runlevel on x start
@@ -2950,11 +3061,13 @@ print_usage()
 	echo "${C}-P${S} Run script with ${C}P${S}roxy settings for connection, requires this syntax:"
 	echo "   ${C}-P http://[<username><:password>@]<server><:port>${S} Argument is required."
 	echo "${C}-U${S} Forces an ${C}U${S}pdate of script before it runs again."
+
 	echo "${C}-x${S} Runs e${C}x${S}tra script features that are not core to central functionality."
 	echo "${C}-X${S} Download and run a custom user script. Syntax: ${C}-X userscript-name#userscript-url"
 	echo "    ${S}Example: ${C}-X my-cleanup-script#somewebsite.com/my-cleanup-script${S}"
 	echo "    The script will show as an additional option in the Post upgrade section."
-
+	echo "${C}-! 20${S} - Triggers update of ALL ${C}$SCRIPT_NAME${S} components, including ${C}$MOD_GFX${S}, ${C}$MOD_VM${S}, and ${C}$MOD_INXI${S}."
+	echo "${C}-! 21${S} - Downloads and installs ${C}rbxi${S} package to ${C}$SCRIPT_HOME."
 	echo
 	echo "${S}The following can be run in X/kde:"
 	echo "${C}-h${S} Prints this ${C}h${S}elp menu."
@@ -2976,6 +3089,7 @@ print_usage()
 		echo "${C}-! 12${S} - Triggers an update from svn branch two - if present, of course."
 		echo "${C}-! <http://......>${S} - Triggers an update from whatever server you list."
 	fi
+	echo
 	echo $LINE
 	echo "${S}Remember: to scroll up or down in terminal window, use: ${C}shift+pageup/pagedown${N}"
 	echo $LINE
@@ -3128,6 +3242,12 @@ get_options()
 							;;
 						12)
 							altScriptUrl=$SCRIPT_DOWNLOAD_BRANCH_2
+							;;
+						20)
+							update_all_scripts
+							;;
+						21)
+							update_all_scripts 'rbxi'
 							;;
 						http*)
 							altScriptUrl=$OPTARG
