updated smxi-stub to use wget -O - to variable pre script download/install to avoid all that messy cleanup stuff, and to make it more reliable overall.

diff --git a/smxi-stub/smxi-stub b/smxi-stub/smxi-stub
--- a/smxi-stub/smxi-stub
+++ b/smxi-stub/smxi-stub
@@ -3,10 +3,10 @@
 ####  Script Name: smxi-stub
 ####  stub installer for smxi scripts
 ####  Only supports true Debian based distros.
-####  version: 2.9
-####  Date: 20 August 2009
+####  version: 3.0
+####  Date: 24 February 2010
 ########################################################################
-####  Copyright (C) Harald Hope, sidux team members 2007-2009
+####  Copyright (C) Harald Hope, sidux team members 2007-2010
 ####
 ####  This program is free software; you can redistribute it and/or modify it under
 ####  the terms of the GNU General Public License as published by the Free Software
@@ -43,8 +43,7 @@ DOWNLOAD_URL_INXI='http://inxi.googlecode.com/svn/trunk/'
 DOWNLOAD_URL_SGFXI='http://smxi.org/sg/'
 DOWNLOAD_URL_SMXI='http://smxi.org/sm/'
 DOWNLOAD_URL_SVMI='http://smxi.org/sv/'
-# Do  not create temp file here. It will create masses of temp files over time.
-FILE_TEMP_NAME='' # will handle failed downloads
+FILE_DATA_TEMP='' # will handle failed downloads
 # this is the tester for ##**EOF**## endings present in scripts, change this
 # if you want to extend this stub to other scripts, smxi/svmi/inxi/sgfxi all use this
 SCRIPT_EOF='##\*\*EOF\*\*##'
@@ -56,32 +55,20 @@ error_handler()
 	case $1 in
 		1)	message='You must be root to run this script!'
 			;;
-		2)	message='Failed to download script properly. The file is empty!'
+		2)	message="Script download exited with errors.\nThe following download url failed with wget error: $2/n$DOWNLOAD_URL$SCRIPT"
 			;;
-		3)	message="$PREFIX$SCRIPT not executable!"
+		3)	message='Failed to download script properly. The file data is corrupted or incomplete!'
 			;;
-		4)	message="Script download exited with errors.\nThe following download url failed with wget error: $2/n$DOWNLOAD_URL$SCRIPT"
+		4)	message="$PREFIX$SCRIPT exec command failed with error number: $2\nPlease try again."
 			;;
-		5)	message='Unknown script requested.'
+		5)	message="$PREFIX$SCRIPT not executable!"
 			;;
-		6)	message='Failed to download script. The downloaded file does not exist!'
-			;;
-		7)	message="$PREFIX$SCRIPT exec command failed with error number: $2\nDeleting problem file. Please try again."
-			# this will handle, I think, partial, incomplete, downloads, that are not null
-			if [ -f "$PREFIX$SCRIPT" ];then
-				rm -f "$PREFIX$SCRIPT"
-			fi
-			;;
-		8)	message='Failed to download script properly. The file is corrupted!'
+		6)	message="Unknown script requested: $CALLER"
 			;;
 		*)	message='Unknown error, exiting now.'
 			;;
 	esac
 	echo -e "Error No: $1 - $message"
-	# cleanup the temp file if error
-	if [ -f "$FILE_TEMP_NAME" ];then
-		rm -f "$FILE_TEMP_NAME"
-	fi
 	exit $1
 }
 
@@ -104,24 +91,14 @@ case $CALLER in
 		DOWNLOAD_URL=$DOWNLOAD_URL_INXI
 		;;
 	*)
-		error_handler 5
+		error_handler 6
 		;;
 esac
 
-# this handles that annoying null file thing. Because -s is ambiguous, I added a -f check
-# as well. Delete all existing null files. This test must be first. This won't handle incomplete
-# downloads, but it will help a bit. This also avoids a file does not exist error
-if [ -f "$PREFIX$SCRIPT" -a ! -s "$PREFIX$SCRIPT" ];then
-	rm -f "$PREFIX$SCRIPT"
-fi
-
-# now that null files are removed, we can safely use the -x test. Note: be very careful
-# relying on -x as a test, null files can have the exec bit set... that's bash for you...
 # if $SCRIPT exists, it will handle the root tests. Root tests cannot
 # be run first because they kill the -h help function
 if [ -x "$PREFIX$SCRIPT" ];then
 	# I'm just going to put a test for basically everything that can go wrong
-	# If we're lucky, this will handle partial or incomplete downloads that are not null
 	exec "$PREFIX$SCRIPT" "$@" || error_handler 7 "$?"
 else
 	# only in case of requirement to download script do root test, and just exit
@@ -129,51 +106,24 @@ else
 	if [ "$( id -u )" -ne 0 ];then
 		error_handler 1
 	fi
-
-	# if and only if file does not exist and user is root do we make the temp file
-	FILE_TEMP_NAME="$( mktemp -p $PREFIX $CALLER.XXXXXXXXXX )"
-	# now we'll use a simple -f test since the null case is already handled. We are not
-	# downloading to overwrite existing file, but to temp file, which we then test for null
-	# -O is risky here too because failed downloads create a null file automatically.
-	if [ ! -f "$PREFIX$SCRIPT" ];then
-		wget -q -O "$FILE_TEMP_NAME" "$DOWNLOAD_URL$SCRIPT" || error_handler 4 "$?"
-	fi
+	# downloading to overwrite existing file, but to temp variable, which we then test
+	FILE_DATA_TEMP="$( wget -q -O - $DOWNLOAD_URL$SCRIPT )" || error_handler 2 "$?"
 	
-	# the primary test is to test for file corruption, if the new file doesn't have
-	# the EOF value, it is by definition corrupted. After that some simple tests.
-	#  -s is prefered over -f because sometimes downloads fail and leave null size file
-	# we're taking the temp file, testing it for null, then mv to correct file. Please do
-	# not mess with these tests at all unless you can make them even more robust. No -f
-	# is required because if wget exits with error then script exits. And if no error,
-	# file will be null or existent and not null. I am adding another -f test here because
-	# wget is so buggy I simply cannot predict its failure behaviors at all.
-	if [ ! -e "$FILE_TEMP_NAME" ];then
-		error_handler 6
-	elif [ ! -s "$FILE_TEMP_NAME" ];then
- 		error_handler 2
- 	# then test for eof marker in files, this is basically foolproof
-	elif [ -z "$( grep -si "$SCRIPT_EOF" $FILE_TEMP_NAME )" ];then
-		error_handler 8
-# 	# if exists and not null
-	# I'm being extra careful here, there have been too many problems with this simple
-	# stuff... wget needs to be fixed to handle failed downloads better... what is  missing
-	# is a null file test, as opposed to exists AND null.
-	elif [ -s "$FILE_TEMP_NAME" ];then
-		# now that the file exists and is not null
-		mv -f $FILE_TEMP_NAME $PREFIX$SCRIPT
-
-		# make executable if not
-		if [ ! -x "$PREFIX$SCRIPT" ];then
-			chmod +x "$PREFIX$SCRIPT"
-		fi
-
+	# test to make sure downloaded data has EOF marker, if yes, it's complete
+	if [ -z "$( grep -si "$SCRIPT_EOF" <<< "$FILE_DATA_TEMP" )" ];then
+		error_handler 3
+	else
+		# now that the data is tested and not corrupted move to real file
+		echo "$FILE_DATA_TEMP" > $PREFIX$SCRIPT
+		# make new file executable
+		chmod +x "$PREFIX$SCRIPT"
 		# then run it with an error handler for unknown weirdness which I'm sure will appear.
 		if [ -x "$PREFIX$SCRIPT" ];then
-			# I'm just going to put a test for basically everything that can go wrong
-			# If we're lucky, this will handle partial or incomplete downloads that are not null
-			exec "$PREFIX$SCRIPT" "$@" || error_handler 7 "$?"
+			# If for some reason it errors on script execution, exit here, but that could be
+			# something as simple as bad options used
+			exec "$PREFIX$SCRIPT" "$@" || error_handler 4 "$?"
 		else
-			error_handler 3
+			error_handler 5
 		fi
 	fi
 fi
